### PR TITLE
Fix link to custom_llms.md

### PR DESCRIPTION
**Pull request by tevino**

### CODE REVIEW

**Review by jerryjliu — CHANGES_REQUESTED** [review]
i don't think this link is broken?

**Comment by tevino** [comment]
@jerryjliu Does the link “[Custom LLMs How-To](https://github.com/jerryjliu/gpt_index/blob/14938721657b70d954fd52509bad24d599e1c9fe/how_to/custom_llms.md)” at the bottom of [this page](https://github.com/jerryjliu/gpt_index/blob/14938721657b70d954fd52509bad24d599e1c9fe/docs/getting_started/installation.md) work for you?

**Comment by jerryjliu** [comment]
> @jerryjliu Does the link “[Custom LLMs How-To](https://github.com/jerryjliu/gpt_index/blob/14938721657b70d954fd52509bad24d599e1c9fe/how_to/custom_llms.md)” at the bottom of [this page](https://github.com/jerryjliu/gpt_index/blob/14938721657b70d954fd52509bad24d599e1c9fe/docs/getting_started/installation.md) work for you?

i would check the readthedocs link https://gpt-index.readthedocs.io/en/latest/how_to/custom_llms.html

**Comment by jerryjliu** [comment]
going to close for now

**Pull request closed without merging**
