### PR TITLE
Refactor instances of query function to allow querying over subset of doc_ids

### PR DESCRIPTION
**Pull request by sandkoan**
I refactored all relevant instances of the query function to include an extra parameter, `doc_ids`, which is a list of `doc_id`s within which to restrict the potential sources for a response.

And I implemented the basic filtering by doc_id functionality for the Qdrant Vector Index.

### CODE REVIEW

**Review by jerryjliu — COMMENTED** [review]
thanks for the PR! i like the high-level concept

in terms of code structure, i'd recommend looking at how the `required_keywords` arg is passed in through `index.query` call down to the query classes. The arg should be a part of the `__init__` for each query class, instead of in the query class `query` call. Then you also don't need to change the function signature of each query class.

I think adding a doc_id filter directly in the qdrant vector index (and other vector indices) makes sense; however, take a look at `_should_use_node` as well in the base query class. having a doc_id filter there could work too - and this will help add doc_id filtering to a lot of our indices/queries out of the box

**Comment by sandkoan** [comment]
But if you end up filtering *after* retrieving the most relevant nodes, is there not a distinct possibility that you end up without any actual nodes for the answer? Let's say there are a number of nodes that are highly relevant, but those are all nodes that we choose to explicitly ignore—then once we post-query filter the nodes, we won't have any nodes left to construct a response. Whereas if we apply the filter *before* querying, then we can find an adequate number of nodes that meet the doc_id filtering criteria.

**Comment by sandkoan** [comment]
Of course, if you still think we should do post-query filtering (which, Qdrant, at least, isn't best optimized for), the solution to the problem of not returning enough nodes is, as I just realized, quite simple: instead of searching for the `top_k` results, search for the `top_2k` results, and filter those.

**Comment by jerryjliu** [comment]
> But if you end up filtering _after_ retrieving the most relevant nodes, is there not a distinct possibility that you end up without any actual nodes for the answer? Let's say there are a number of nodes that are highly relevant, but those are all nodes that we choose to explicitly ignore—then once we post-query filter the nodes, we won't have any nodes left to construct a response. Whereas if we apply the filter _before_ querying, then we can find an adequate number of nodes that meet the doc_id filtering criteria.
> 
> Or are you suggesting we do both? Because it appears highly trivial to implement what you suggested—just a 5 line change—but it seems to me like it would lead to unintuitive behaviour.

oh that's a good point. that's more due to the fact that the current placement of _should_use_node is not ideal, i can take a look at changing that. but regardless, i think we should put this param in the __init__ of the query class, similar to required_keywords

**Comment by sandkoan** [comment]
Alright, sounds good. As long as we apply the filter pre-query as opposed to post-query, we shouldn't run into any problems.

**Comment by jerryjliu** [comment]
@sandkoan can this PR be closed now?

**Pull request closed without merging**
