### PR TITLE
Adds an AsanaReader for loading tasks from a workspace

### PR DESCRIPTION
**Pull request by daveey**

### CODE REVIEW

**Comment by ahmetkca** [comment]
Hi @daveey, thanks for the reader. The only comment I have is. We can make the `asana_token` optional and get it from environment variable, if it is not provided. It is up to you.

**Comment by emptycrown** [comment]
Awesome! Would you be able to port this over to https://github.com/emptycrown/llama-hub? We're porting over all the readers to a dedicated library over there.

Incidentally, we're drawing prizes for all new creators of loaders before 2/24 so this would be a great fit.

**Comment by jerryjliu** [comment]
@daveey thanks for this PR! 

If you have questions on migrating to llamahub, no problem. ping us and we're more than happy to help out

**Comment by daveey** [comment]
I added a PR to llamahub, but was unable to test it:

>>> from gpt_index import download_loader
>>> AsanaReader = download_loader('AsanaReader')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/daveey/code/gpt_index/gpt_index/readers/download.py", line 56, in download_loader
    raise ValueError("Loader class name not found in library")
ValueError: Loader class name not found in library

I assume this is because the PR has to first be merged?

**Comment by emptycrown** [comment]
Yeah, has to be merged first. Typically it's enough to just test the class itself in a notebook. Taking a look now, thanks!

**Comment by daveey** [comment]
> Hi @daveey, thanks for the reader. The only comment I have is. We can make the `asana_token` optional and get it from environment variable, if it is not provided. It is up to you.

I can do that if you feel strongly, but personally I prefer that users explicitly specify auth tokens rather than relying on ENV.

**Comment by daveey** [comment]
Closing in favor of https://github.com/emptycrown/llama-hub/pull/38

**Comment by ahmetkca** [comment]
> I added a PR to llamahub, but was unable to test it:
> 
> 
> 
> >>> from gpt_index import download_loader
> 
> >>> AsanaReader = download_loader('AsanaReader')
> 
> Traceback (most recent call last):
> 
>   File "<stdin>", line 1, in <module>
> 
>   File "/Users/daveey/code/gpt_index/gpt_index/readers/download.py", line 56, in download_loader
> 
>     raise ValueError("Loader class name not found in library")
> 
> ValueError: Loader class name not found in library
> 
> 
> 
> I assume this is because the PR has to first be merged?

You can actually point to your fork and temporarily test before merging.

**Pull request closed without merging**
