### PR TITLE
Allow passing table parameter to GPTSQLStructStoreIndex

### PR DESCRIPTION
**Pull request by cwelton**
PR to address: https://github.com/jerryjliu/gpt_index/issues/203

Core issue:  In SQLAlchemy `MetaData(bind=self._engine).reflect()` only returns metadata for tables, not views.

However, it is still possible to get view metadata explicitly with
```
my_view = Table('some_view', MetaData(bind=engine), autoload=True)
```
See https://docs.sqlalchemy.org/en/14/core/reflection.html#reflecting-views for details

Amongst the suggestions in that documentation is that for views you may want to specific additional context, such as hints on primary and foreign keys:
```
my_view = Table(
    "some_view",
    metadata,
    Column("view_id", Integer, primary_key=True),
    Column("related_thing", Integer, ForeignKey("othertable.thing_id")),
    autoload_with=engine,
)
```

So we have one possible option of simply replacing 
```
table = self.sql_database.metadata_obj.tables[table_name]
```
with
```
table = Table(tablename, autolad_with=engine)
```
However the issue with that is that it doesn't allow us to easily specify those primary and foreign key constraints easily. (*)

Which leads to the approach taken here: allow the creator of the GPTSQLStructStoreIndex to pass the `table` structure in instead of the `table_name`.

(*) That said there is a general case performance improvement that we could make by doing this in favor of the full `metadata_obj.reflect()` that currently exists in the SQLDatabase object.  We only need metadata for the one table, and the full reflect() will do the entire schema.  This is outside the scope of what this PR is trying to achieve, so is not included.

### CODE REVIEW

**Comment by cwelton** [comment]
To test:

```
# This fails with a KeyError trying to lookup `metadata.tables['my_view']`
index = GPTSQLStructStoreIndex(
    documents=[],
    sql_engine=engine,
    table_name='my_view',
)

# This succeeds and produces a usable index
index = GPTSQLStructStoreIndex(
    documents=[],
    sql_engine=engine,
    table= Table('my_view', MetaData(bind=engine), autoload=True)
)
```

**Comment by jerryjliu** [comment]
this is amazing! will get to this tonight

**Comment by cwelton** [comment]
There is a lint failure here.  I think resulting from:
```
        table: Optional[Table] = None,
...
        self.table_name = table_name or table.name
```

Which *could* result in us trying to get `table.name` of None, that would of course fail.

In practice... not super likely
```
        if table_name is None and table is None:
            raise ValueError("table_name must be specified")
        self.table_name = table_name or table.name
```
Should ensure that if table_name is present we'll use that, if it's not present then we would have already errored with the ValueError.  

But its still theoretically valid if table_name == '', 0, or some other falsey but not None value.

**Comment by jerryjliu** [comment]
> There is a lint failure here. I think resulting from:
> 
> ```
>         table: Optional[Table] = None,
> ...
>         self.table_name = table_name or table.name
> ```
> 
> Which _could_ result in us trying to get `table.name` of None, that would of course fail.
> 
> In practice... not super likely
> 
> ```
>         if table_name is None and table is None:
>             raise ValueError("table_name must be specified")
>         self.table_name = table_name or table.name
> ```
> 
> Should ensure that if table_name is present we'll use that, if it's not present then we would have already errored with the ValueError.
> 
> But its still theoretically valid if table_name == '', 0, or some other falsey but not None value.

a `cast` should work - i can help with that, one sec

**Pull request merged**
