### PR TITLE
Add DONUT model for parsing image documents

### PR DESCRIPTION
**Pull request by ravi03071991**
Hi,

Made a PR for parsing image documents that contain a lot of (key, value) pairs of information in the images. gpt-index can directly query on top of this to answer values wrt certain keys.

Regards,
Ravi Theja.

### CODE REVIEW

**Review by jerryjliu — COMMENTED** [review]
@ravi03071991 this generally looks good. It may have a conflict with https://github.com/jerryjliu/gpt_index/pull/219 though (which I want to land first), so will ping you when that lands

**Comment by ravi03071991** [comment]
sure.

**Comment by jerryjliu** [comment]
> sure.

that PR is landed, feel free to merge

**Comment by ravi03071991** [comment]
Duplicate of imageparser branch. Closing this branch.

**Pull request closed without merging**
