### PR TITLE
correcting behavior of upsert

### PR DESCRIPTION
**Pull request by Ryanglambert**
We shouldn't generate random IDs when we upsert into pinecone. (that is not the behavior of upserting)

### CODE REVIEW

**Comment by Ryanglambert** [comment]
all tests pass on this for me locally

**Comment by jerryjliu** [comment]
> all tests pass on this for me locally

this is a good point. the function is more suppose to be an `insert` than an upsert one. can help take a look

**Comment by Ryanglambert** [comment]
Upsert (if it's not there, put it there, if it already is then overwrite it)

**Comment by Ryanglambert** [comment]
otherwise you end up with the same document insertion creating another vector in the db

**Comment by jerryjliu** [comment]
> otherwise you end up with the same document insertion creating another vector in the db

that's a fair point

**Review by jerryjliu — APPROVED** [review]

**Pull request merged**
